---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: default
type: Opaque
data:
  db: d29yZHByZXNz
  user: d29yZHByZXNz
  password: cGFzc3dvcmQ=
  root-password: cGFzc3dvcmQ=
