---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-wp
  namespace: default
type: Opaque
data:
  MYSQL_USER: d29yZHByZXNz
  MYSQL_PASSWORD: YWRtaW4=