version: '3.9'
services:
  jenkins-server:
    depends_on:
      - jenkins-docker
    image: ${DOCKER_REGISTRY}/jenkins-server:latest
    container_name: jenkins-server
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: tcp://jenkins-docker:2375
      DOCKER_CERT_PATH: ""
      DOCKER_TLS_VERIFY: ""
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    restart: unless-stopped
    ports:
      - 2375:2375
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network
  # jenkins-slave:
  #   image: jenkins/inbound-agent
  #   container_name: jenkins-slave
  #   init: true
  #   restart: unless-stopped
  #   environment:
  #     JENKINS_URL: http://jenkins-server:8080
  #     JENKINS_SECRET: 55245acd37145200a7e384e8721367db33cc6be86cc1e7da64ec716f554ad3f8
  #     JENKINS_AGENT_NAME: worker
  #     JENKINS_AGENT_WORKDIR: /home/jenkins/agent
  #   networks:
  #     - jenkins-network

volumes:
  jenkins-data:

networks:
  jenkins-network: