apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.statefulsetMysqlName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db: {{ .Values.secrets.db }}
  user: {{ .Values.secrets.user }}
  password: {{ .Values.secrets.password }}
  rootpassword: {{ .Values.secrets.rootpassword }}
